In [86]:
import pandas as pd
asistencia=pd.read_csv('Check-ins eventos_10-08-2025.csv')
asistencia.head()

,Member Name,Impulsa Tu Negocio TO - Tercera Edición 2025 (2025-09-27),"Inteligencia Artificial: Puerta al Futuro, Retos del Presente (2025-09-13)",Fortalece Tu Marca Profesional en LinkedIn (2025-09-10),Tarde de Yoga! (2025-09-06),Tarde de Conexiones en Niagara Falls (2025-09-06),"Sunset Social: ¡Conecta, comparte y ríe! (2025-08-23)","Tarde de Conexiones: Conexiones, Historias y Amigos (2025-08-15)",¡La Red de Hispanos Llega a la Ciudad Vaquera de Canadá! (2025-08-09),"Tarde de Picnic: Cultura, Conexión y Comunidad! (2025-07-12)",...,"Tu Firma, el baúl de tu Secretos (2023-07-13)","Directo de Instagram ""Los 21 secretos de un Resume efectivo"" (2023-07-12)",Diseña tu destino: Fotos Para Perfil de LinkedIn (2023-07-11),Evita 5 Errores Comunes de Fotos de Perfil en LinkedIn (2023-07-05),CELEBRACIÓN DEL DÍA DEL YOGA (2023-06-25),Evento Social de La Red de Hispan@s (2023-06-16),Professional Networking Event: Let's Connect with Swoon (2023-05-18),After Work - La Red de Hispan@s (2023-04-20),"Jornadas Informativas de la Consejería de Trabajo, Migraciones (2023-03-30)",Evento Social de La Red de Hispan@s en Toronto (2023-03-25)
0,NaN,2025-09-27,2025-09-13,2025-09-10,2025-09-06,2025-09-06,2025-08-23,2025-08-15,2025-08-09,2025-07-12,...,2023-07-13,2023-07-12,2023-07-11,2023-07-05,2023-06-25,2023-06-16,2023-05-18,2023-04-20,2023-03-30,2023-03-25
1,Raquel Narvajas,1,1,1,0,0,1,1,1,1,...,1,1,1,1,1,1,1,1,0,1
2,Luis Sepulveda,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Antonio Peláez Barceló,0,1,0,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,Carlos Varela,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [87]:
#The first row is deleted from the dataset
asistencia = asistencia.drop(asistencia.index[0])
asistencia.head()

,Member Name,Impulsa Tu Negocio TO - Tercera Edición 2025 (2025-09-27),"Inteligencia Artificial: Puerta al Futuro, Retos del Presente (2025-09-13)",Fortalece Tu Marca Profesional en LinkedIn (2025-09-10),Tarde de Yoga! (2025-09-06),Tarde de Conexiones en Niagara Falls (2025-09-06),"Sunset Social: ¡Conecta, comparte y ríe! (2025-08-23)","Tarde de Conexiones: Conexiones, Historias y Amigos (2025-08-15)",¡La Red de Hispanos Llega a la Ciudad Vaquera de Canadá! (2025-08-09),"Tarde de Picnic: Cultura, Conexión y Comunidad! (2025-07-12)",...,"Tu Firma, el baúl de tu Secretos (2023-07-13)","Directo de Instagram ""Los 21 secretos de un Resume efectivo"" (2023-07-12)",Diseña tu destino: Fotos Para Perfil de LinkedIn (2023-07-11),Evita 5 Errores Comunes de Fotos de Perfil en LinkedIn (2023-07-05),CELEBRACIÓN DEL DÍA DEL YOGA (2023-06-25),Evento Social de La Red de Hispan@s (2023-06-16),Professional Networking Event: Let's Connect with Swoon (2023-05-18),After Work - La Red de Hispan@s (2023-04-20),"Jornadas Informativas de la Consejería de Trabajo, Migraciones (2023-03-30)",Evento Social de La Red de Hispan@s en Toronto (2023-03-25)
1,Raquel Narvajas,1,1,1,0,0,1,1,1,1,...,1,1,1,1,1,1,1,1,0,1
2,Luis Sepulveda,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Antonio Peláez Barceló,0,1,0,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,Carlos Varela,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,Lucía Sanz,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,1,0,0,1

In [88]:
#The columns are converted in rows for future analysis
asistencia_larga=asistencia.melt(
    id_vars=['Member Name'],          
    var_name='Evento',            
    value_name='Asistencia'
)

print("\nDataFrame after melt:")
asistencia_larga.head()

DataFrame after melt:

,Member Name,Evento,Asistencia
0,Raquel Narvajas,Impulsa Tu Negocio TO - Tercera Edición 2025 (...,1
1,Luis Sepulveda,Impulsa Tu Negocio TO - Tercera Edición 2025 (...,0
2,Antonio Peláez Barceló,Impulsa Tu Negocio TO - Tercera Edición 2025 (...,0
3,Carlos Varela,Impulsa Tu Negocio TO - Tercera Edición 2025 (...,0
4,Lucía Sanz,Impulsa Tu Negocio TO - Tercera Edición 2025 (...,0

In [89]:
# The column 'Evento' contains the name of the event and the date
# In the folowing lines, the column is splited between Evento and Fecha
split_name_date = asistencia_larga['Evento'].str.split('(', n=1, expand=True)
asistencia_larga['Fecha']=split_name_date[1]

#The column 'Fecha' is cleaned, This removes everything that is NOT a digit or a dash from anywhere in the string
asistencia_larga['Fecha'] = asistencia_larga['Fecha'].str.replace(r'[^\d\-]', '', regex=True)

# Display the updated DataFrame
print("\nDataFrame after splitting:")
print(asistencia_larga)

DataFrame after splitting:
                  Member Name  \
0             Raquel Narvajas
1              Luis Sepulveda
2      Antonio Peláez Barceló
3               Carlos Varela
4                  Lucía Sanz
...                       ...
88887           Fernando Vega
88888     Fernando De La Peña
88889              Rene Irias
88890           Alvaro Rivero
88891          Isabella Abols

                                                  Evento Asistencia  \
0      Impulsa Tu Negocio TO - Tercera Edición 2025 (...          1
1      Impulsa Tu Negocio TO - Tercera Edición 2025 (...          0
2      Impulsa Tu Negocio TO - Tercera Edición 2025 (...          0
3      Impulsa Tu Negocio TO - Tercera Edición 2025 (...          0
4      Impulsa Tu Negocio TO - Tercera Edición 2025 (...          0
...                                                  ...        ...
88887  Evento Social de La Red de Hispan@s en Toronto...          0
88888  Evento Social de La Red de Hispan@s en Toronto...          0
88889  Evento Social de La Red de Hispan@s en Toronto...          0
88890  Evento Social de La Red de Hispan@s en Toronto...          0
88891  Evento Social de La Red de Hispan@s en Toronto...          0

            Fecha
0      2025-09-27
1      2025-09-27
2      2025-09-27
3      2025-09-27
4      2025-09-27
...           ...
88887  2023-03-25
88888  2023-03-25
88889  2023-03-25
88890  2023-03-25
88891  2023-03-25

[88892 rows x 4 columns]

In [90]:
# Create a temporary series to test the conversion
tested_dates = pd.to_datetime(asistencia_larga['Fecha'], errors='coerce')

# Filter the original table to see ONLY where the conversion failed
errors = asistencia_larga[tested_dates.isna()]

# Show the unique values that are causing the problem
print("Values that do not have the correct format:")
print(errors['Fecha'].unique())

Values that do not have the correct format:
[]

In [91]:
# Shows the current data type to see if it's necessary a future type transformation 
asistencia_larga.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88892 entries, 0 to 88891
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Member Name  88892 non-null  object
 1   Evento       88892 non-null  object
 2   Asistencia   88892 non-null  object
 3   Fecha        88892 non-null  object
dtypes: object(4)
memory usage: 2.7+ MB

In [92]:
# Data Type modification
# Convert attendance to numbers (for future calcules)
asistencia_larga['Asistencia'] = asistencia_larga['Asistencia'].astype(int)

# Convert date to real time (for future analysis)
asistencia_larga['Fecha'] = pd.to_datetime(asistencia_larga['Fecha'])

# verification type modification
print(asistencia_larga.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88892 entries, 0 to 88891
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Member Name  88892 non-null  object
 1   Evento       88892 non-null  object
 2   Asistencia   88892 non-null  int64
 3   Fecha        88892 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 2.7+ MB
None

In [93]:
# Create a table that summarize per event, how many people attented
Event_Attendance=asistencia_larga.pivot_table(index='Evento',values='Asistencia', aggfunc='sum')
Event_Attendance.sort_values(by='Asistencia', ascending=False, inplace=True)
Event_Attendance

                                                    Asistencia
Evento
Spring Party: Donde las Conexiones y el Buen Cl...          55
Evento Social: Celebración de Navidad (2023-12-08)          52
Winter Party: Liberemos el Estrés (2025-02-22)              49
Segunda Feria Hispana con Organizaciones Sin Fi...          49
Evento Social: Halloween (2023-10-27)                       43
...                                                        ...
Swoon and La Red de Hispan@s: Network with us! ...           1
Taller de Lectura y Escritura Creativa con Norb...           1
Taller de Lectura y Escritura Creativa con Norb...           1
Taller de Lectura y Escritura Creativa con Norb...           1
¡Los Lunes Toca Ser Red! (2023-11-27)                        1

[142 rows x 1 columns]

In [98]:
# Importing second database from Evenbrite

# List to keep columns I just want to import
eventbrite_df = pd.read_csv('Attendees_EvenBrite.csv', encoding='mac_roman')
cols_to_keep = ['Attendee first name','Attendee last name','Event name','Event start date']  
eventbrite_df = eventbrite_df[cols_to_keep]
eventbrite_df.head()

,Attendee first name,Attendee last name,Event name,Event start date
0,Gen,G,Día Internacional de La Mujer: Latinas en Polí...,2024-03-08
1,Gen,G,Día Internacional de La Mujer: Latinas en Polí...,2024-03-08
2,Miriam,Arteaga,Día Internacional de La Mujer: Latinas en Polí...,2024-03-08
3,Miriam,Arteaga,Día Internacional de La Mujer: Latinas en Polí...,2024-03-08
4,Liliana,Altamirano,Día Internacional de La Mujer: Latinas en Polí...,2024-03-08

In [99]:
# Convert date to real time (for future analysis)
eventbrite_df['Event start date'] = pd.to_datetime(eventbrite_df['Event start date'])
eventbrite_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 389 entries, 0 to 388
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Attendee first name  388 non-null    object
 1   Attendee last name   388 non-null    object
 2   Event name           388 non-null    object
 3   Event start date     388 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 12.3+ KB

In [ ]:
# See what event names you have in each dataset (Heylo and Evenbrite)
print("=== Eventbrite ===")
print(eventbrite_df['Event name'].unique())

print("\n=== Heylo ===")
print(asistencia_larga['Evento'].unique())

=== Eventbrite ===
['Día Internacional de La Mujer: Latinas en Política Canadiense'
 'El Periodismo en Canadá: Desafíos y Oportunidades'
 'Innovaciones en el futuro del Transporte Público en Canadá'
 'Crea tu Negocio Navegando las Estructuras de Negocio en Canadá'
 'Winter Party: Liberemos el Estrés'
 'Mujeres Hispanas en el Sector de la Educación - Día de la Mujer'
 'Transforma tu Futuro: Optimiza tu Perfil de LinkedIn'
 'Tu Camino al Éxito en Canada con CIMT College'
 'Segunda Feria Hispana con Organizaciones Sin Fines de Lucro'
 'Spring Party: Donde las Conexiones y el Buen Clima se Encuentran'
 'SPEED NETWORKING DONDE LAS CONEXIONES CREAN OPORTUNIDADES REALES'
 'Tarde de Picnic: Cultura, Conexión y Comunidad!'
 'Sunset Social: ¡Conecta, comparte y ríe!'
 '¡La Red de Hispanos Llega a la Ciudad Vaquera de Canadá!'
 'Impulsa Tu Negocio TO - Tercera Edición 2025' 'Tarde de Yoga'
 'Tarde de Conexiones en Niagara Falls'
 'Fortalece Tu Marca Profesional en Linkedin'
 'Conecta y Crece: Recomendaciones Inteligentes en La Red'
 'Cómo los Jóvenes pueden Prosperar en la Era de la IA'
 'De Migrante a Líder: La Trayectoria de Miguel A.López'
 'Speak Dating: Inglés y Francés'
 'Domina el CELPIP: Claves para tu éxito en Canadá'
 'Cata de Cervezas Artesanales'
 'Canadá a través del arte: Tour guiado en español.' 'Gala Hispana 2025'
 'El poder del español: How Spanish Got Me a Job'
 'Oportunidades Laborales en Canadá con Grupo Cartago'
 'Evento Social Hispano en Calgary' 'Evento Social Hispano en Ottawa'
 'Winter Party' 'Evento Social Hispano en Montreal'
 'Revoluciona tu Mundo: Chatbot & AI' 'Speak Dating'
 'Guía para emprender sin miedo en Canada' nan]

=== Heylo ===
['Impulsa Tu Negocio TO - Tercera Edición 2025 (2025-09-27)'
 'Inteligencia Artificial: Puerta al Futuro, Retos del Presente (2025-09-13)'
 'Fortalece Tu Marca Profesional en LinkedIn (2025-09-10)'
 'Tarde de Yoga! (2025-09-06)'
 'Tarde de Conexiones en Niagara Falls (2025-09-06)'
 'Sunset Social: ¡Conecta, comparte y ríe! (2025-08-23)'
 'Tarde de Conexiones: Conexiones, Historias y Amigos (2025-08-15)'
 '¡La Red de Hispanos Llega a la Ciudad Vaquera de Canadá! (2025-08-09)'
 'Tarde de Picnic: Cultura, Conexión y Comunidad! (2025-07-12)'
 'Noche de Encuentros: Charla, Risas y Networking (2025-07-09)'
 'SPEED NETWORKING DONDE LAS CONEXIONES CREAN OPORTUNIDADES REALES (2025-06-21)'
 'Spring Party: Donde las Conexiones y el Buen Clima se Encuentran (2025-05-10)'
 'Segunda Feria Hispana con Organizaciones Sin Fines de Lucro (2025-05-03)'
 'Transforma tu Futuro: Optimiza tu Perfil de LinkedIn (2025-04-08)'
 'Tu Camino al Éxito en Canada con CIMT College (2025-03-28)'
 'Cómo Construir una Carrera Exitosa en la Industria del Fútbol (2025-03-12)'
 'Mujeres Hispanas en el Sector de la Educación - Día de la Mujer (2025-03-08)'
 'Cursos de francés con FutureOn Solutions (2025-03-06)'
 'Comenzar una Empresa Pequeña en Canadá (2025-03-01)'
 'Winter Party: Liberemos el Estrés (2025-02-22)'
 'La Importancia de Hacer tus Impuestos en Canadá (2025-02-18)'
 'Aprende a Dominar la Inteligencia Artificial (2025-02-08)'
 'Conecta con Profesionales del Ámbito Científico y Tecnológico (2025-02-06)'
 'Impulsa tu Carrera con una Certificación\xa0en\xa0IA (2025-01-25)'
 'Crea tu Negocio Navegando las Estructuras de Negocio en Canadá (2025-01-22)'
 'Rosca de Reyes y Karaoke (2025-01-08)'
 'Primera Gala de Fin de Año de La Red de Hispanos (2024-12-06)'
 'Evento para Emprendedores: Funding Small Business (2024-11-25)'
 '🌟 Primer Evento Presencial de La Red de Hispanos en Ottawa 💫 (2024-11-23)'
 'Evento de Wellness con Ana- Fitness Dance (2024-11-16)'
 'Evento Social - Noche de Karaoke (2024-11-06)'
 'EVENTO PARA EMPRENDEDORES - MINDSET AS AN ENTREPRENEUR (2024-10-29)'
 'Impulsa Tu NegocioTO: Segunda Edición 2024 (2024-10-26)'
 'El Periodismo en Canadá: Desafíos y Oportunidades (2024-10-22)'
 'Innovaciones en el futuro del Transporte Público en Canadá (2024-10-15)'
 'Evento para Emprendedores con Vision 2 Reality (2024-09-30)'
 'Evento de Coaching: Taller de Linkedin (2024-09-12)'
 'Noche de Micrófonos: Comedia & Karaoke (2024-09-04)'
 'Evento de Wellness con Ana (2024-08-24)'
 'Evento Social: Dia de Playa (2024-08-10)'
 'Evento de Networking: Oportunidades Laborales en Transportación (2024-08-01)'
 'Evento Social: Picnic en Toronto Islands (2024-07-27)'
 'Evento Social: Tour por Edwards Gardens (2024-07-20)'
 'Evento de Networking con Swoon (2024-07-11)'
 'Evento Networking: Oportunidades Laborales en Compras (2024-06-20)'
 'Evento Social: Paseo y Picnic en el Lago (2024-06-15)'
 'Evento Social Karaoke (2024-05-15)'
 'Los Lunes Toca Ser Red: Conociendo La Red de Hispanos (2024-05-13)'
 'Feria de Conexión Hispana con Organizaciones sin Fines de Lucro (2024-05-04)'
 'Coaching para Emprendedores: License and Permit for Business (2024-04-29)'
 'Evento Social: Noche de Bingo (2024-04-26)'
 'Estudiar y Trabajar en Canadá con FutureON (2024-04-25)'
 'Coaching Migratorio: Cambios en los Permisos de Estudios y PGWP (2024-04-15)'
 'Cómo Ser un Buen Líder en un Ambiente Multicultural (2024-04-12)'
 'Los Lunes Toca Ser Red: "Vision 2 Reality" con Teresa Shi (2024-03-25)'
 'Vive la Experiencia Canadiense y Potencia tu Educación (2024-03-20)'
 'Evento Social: Karaoke (2024-03-13)'
 'Conmemoración Día Internacional de la Mujer (2024-03-08)'
 'Evento Deportivo: Club de Patinaje de La Red (2024-03-06)'
 'Los Lunes Toca Ser Red: Norberto Rosalez (2024-03-04)'
 'Evento Deportivo: Club de Patinaje de La Red (2024-02-28)'
 'Los Lunes Toca Ser Red: "Vision 2 Reality" con Winnie Hsu (2024-02-26)'
 'Taller de Lectura y Escritura Creativa con Norberto Rosalez (2024-02-23)'
 'Toronto Job Market in 2024 (2024-02-22)'
 'Evento Deportivo: Club de Patinaje de La Red (2024-02-21)'
 'Evento Social: Noche de Trivia (2024-02-16)'
 'Los Lunes Toca Ser Red: "Mothers to Daughters" (Inglés) (2024-02-12)'
 'Taller de Lectura y Escritura Creativa con Norberto Rosalez (2024-02-09)'
 'Evento Deportivo: Club de Patinaje de La Red (2024-02-07)'
 'Los Lunes Toca Ser Red: Casta Latina (2024-02-05)'
 'Evento Deportivo: Club de Patinaje de La Red (2024-01-31)'
 'Los Lunes Toca ser Red: Monica Losno: RRSP season (2024-01-29)'
 'Taller de Lectura y Escritura Creativa con Norberto Rosalez (2024-01-26)'
 'Evento Networking: Taller LinkedIn (2024-01-25)'
 'Evento Deportivo: Club de Patinaje de La Red (2024-01-24)'
 'Los Lunes Toca Ser Red: Vision 2 Reality Foundation (Inglés) (2024-01-22)'
 'Evento Social: BINGO (2024-01-19)'
 'Evento Deportivo: Club de Patinaje de La Red (2024-01-17)'
 'Evento Coaching: Los Lunes Toca Ser Red con ACCES Employment (2024-01-15)'
 'Taller de Lectura y Escritura Creativa con Norberto Rosalez (2024-01-12)'
 'Evento Social: Karaoke (2024-01-10)'
 'Los Lunes Toca Ser Red: Cómo Establecer tus metas para 2024 (2024-01-08)'
 'Visita al mercado navideño del "Distillery District" (2023-12-14)'
 '¡Los Lunes Toca Ser Red! (2023-12-11)'
 'Evento Social: Celebración de Navidad (2023-12-08)'
 'Evento Deportivo: La Red Club de Patinaje (2023-12-06)'
 '¡Los Lunes Toca Ser Red! (2023-12-04)'
 'Evento Deportivo: La Red Club de Patinaje (2023-11-29)'
 '¡Los Lunes Toca Ser Red! (2023-11-27)'
 'IMPULSA TU NEGOCIOTO (2023-11-25)'
 'Networking Event: Connect & Converse with Axelle & Ivy (2023-11-23)'
 '¡Los Lunes Toca Ser Red! con Celeste: Winter Blues (2023-11-20)'
 'Evento Social: Trivia Night! (2023-11-18)'
 'Taller de Lectura y Escritura Creativa con Norberto Rosalez (2023-11-17)'
 'Inmigración: Programa Caregiver para Conseguir tu Residencia (2023-11-16)'
 'Evento Deportivo: La Red Running Club (2023-11-15)'
 'Sistema de Pensiones Canadiense: Punto de Vista del Inmigrante (2023-11-15)'
 '¡Los Lunes Toca Ser Red! (2023-11-13)'
 'Evento Deportivo: La Red Running Club (2023-11-09)'
 'Evento Social: Karoke Red (2023-11-08)'
 '¡Los Lunes Toca Ser Red con Carolina Dávila! (2023-11-06)'
 'Taller de Lectura y Escritura Creativa con Norberto Rosalez (2023-11-03)'
 'Inmigración: Express Entry – Bases con Nuevos Cambios y Programa (2023-11-01)'
 '¡Los Lunes Toca Ser Red! (2023-10-30)'
 'Evento Social: Halloween (2023-10-27)'
 'Evento Deportivo: La Red Running Club (2023-10-25)'
 '¡Los Lunes Toca Ser Red! (2023-10-23)'
 'Taller de Lectura y Escritura Creativa con Norberto Rosalez (2023-10-20)'
 'How to Stand Out in the Canadian Professional Market (2023-10-19)'
 '¡Los Lunes Toca Ser Red! (2023-10-16)'
 '¡Los Lunes Toca Ser Red! (2023-10-10)'
 'Evento Familiar: Paseo en High Park (2023-10-08)'
 'El uso del Humor para incrementar la productividad (2023-10-04)'
 '¡Los Lunes Toca Ser Red! (2023-10-02)'
 'Network with us: Swoon and La Red de Hispanos (2023-09-28)'
 '¡Los Lunes Toca Ser Red! (2023-09-25)'
 'Evento Social: La Red de Hispanos (2023-09-22)'
 '¡Los Lunes Toca Ser Red! (2023-09-18)'
 '¡Los Lunes Toca Ser Red! (2023-09-11)'
 'Descubre tu Gigante Interior: Un Camino hacia el Éxito (2023-09-09)'
 'RUMBO DESCONOCIDO: EL QUE CAMBIA DE LUGAR CAMBIA DE SUERTE (2023-09-01)'
 'Swoon and La Red de Hispan@s: Network with us! (2023-08-17)'
 'Tu firma, el baúl de tus secretos (2023-08-10)'
 'Directo de Instagram "Los 21 secretos de un Resume efectivo" (2023-08-09)'
 'Tu firma, el baúl de tus secretos (2023-08-03)'
 'Directo de Instagram "Los 21 secretos de un Resume efectivo" (2023-08-02)'
 'Evento Social de La Red de Hispan@s - Potluck (2023-07-28)'
 'Tu firma, el baúl de tus secretos (2023-07-27)'
 'Directo de Instagram "Los 21 secretos de un Resume efectivo" (2023-07-26)'
 'Tu firma, el baúl de tus secretos (2023-07-20)'
 'Directo de Instagram "Los 21 secretos de un Resume efectivo" (2023-07-19)'
 'A Tribute to Fluffy (2023-07-14)'
 'Tu Firma, el baúl de tu Secretos (2023-07-13)'
 'Directo de Instagram "Los 21 secretos de un Resume efectivo" (2023-07-12)'
 'Diseña tu destino: Fotos Para Perfil de LinkedIn (2023-07-11)'
 'Evita 5 Errores Comunes de Fotos de Perfil en LinkedIn (2023-07-05)'
 'CELEBRACIÓN DEL DÍA DEL YOGA (2023-06-25)'
 'Evento Social de La Red de Hispan@s (2023-06-16)'
 "Professional Networking Event: Let's Connect with Swoon (2023-05-18)"
 'After Work - La Red de Hispan@s (2023-04-20)'
 'Jornadas Informativas de la Consejería de Trabajo, Migraciones (2023-03-30)'
 'Evento Social de La Red de Hispan@s en Toronto (2023-03-25)']

In [103]:
# Clean both columns for comparison, dropping NaN values
eb_names = set(
    eventbrite_df['Event name']
    .dropna()
    .str.replace(r'\s*\(.*?\)', '', regex=True)
    .str.strip()
    .unique()
)

heylo_names = set(
    asistencia_larga['Evento']
    .dropna()
    .unique()
)

# Events that match exactly
exact_matches = eb_names & heylo_names
print("=== EXACT MATCHES ===")
for e in sorted(exact_matches):
    print(f"  ✓ {e}")

# Events in Eventbrite that DON'T match Heylo
print("\n=== EVENTBRITE ONLY (no match) ===")
for e in sorted(eb_names - heylo_names):
    print(f"  ? {e}")

=== EXACT MATCHES ===

=== EVENTBRITE ONLY (no match) ===
  ? Canadá a través del arte: Tour guiado en español.
  ? Cata de Cervezas Artesanales
  ? Conecta y Crece: Recomendaciones Inteligentes en La Red
  ? Crea tu Negocio Navegando las Estructuras de Negocio en Canadá
  ? Cómo los Jóvenes pueden Prosperar en la Era de la IA
  ? De Migrante a Líder: La Trayectoria de Miguel A.López
  ? Domina el CELPIP: Claves para tu éxito en Canadá
  ? Día Internacional de La Mujer: Latinas en Política Canadiense
  ? El Periodismo en Canadá: Desafíos y Oportunidades
  ? El poder del español: How Spanish Got Me a Job
  ? Evento Social Hispano en Calgary
  ? Evento Social Hispano en Montreal
  ? Evento Social Hispano en Ottawa
  ? Fortalece Tu Marca Profesional en Linkedin
  ? Gala Hispana 2025
  ? Guía para emprender sin miedo en Canada
  ? Impulsa Tu Negocio TO - Tercera Edición 2025
  ? Innovaciones en el futuro del Transporte Público en Canadá
  ? Mujeres Hispanas en el Sector de la Educación - Día de la Mujer
  ? Oportunidades Laborales en Canadá con Grupo Cartago
  ? Revoluciona tu Mundo: Chatbot & AI
  ? SPEED NETWORKING DONDE LAS CONEXIONES CREAN OPORTUNIDADES REALES
  ? Segunda Feria Hispana con Organizaciones Sin Fines de Lucro
  ? Speak Dating
  ? Speak Dating: Inglés y Francés
  ? Spring Party: Donde las Conexiones y el Buen Clima se Encuentran
  ? Sunset Social: ¡Conecta, comparte y ríe!
  ? Tarde de Conexiones en Niagara Falls
  ? Tarde de Picnic: Cultura, Conexión y Comunidad!
  ? Tarde de Yoga
  ? Transforma tu Futuro: Optimiza tu Perfil de LinkedIn
  ? Tu Camino al Éxito en Canada con CIMT College
  ? Winter Party
  ? Winter Party: Liberemos el Estrés
  ? ¡La Red de Hispanos Llega a la Ciudad Vaquera de Canadá!

In [ ]:
# !pip install thefuzz

Requirement already satisfied: thefuzz in c:\users\jahil\python projects\ml_env\lib\site-packages (0.22.1)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.0.0 in c:\users\jahil\python projects\ml_env\lib\site-packages (from thefuzz) (3.14.3)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [105]:
from thefuzz import process

# For each Eventbrite name, find the closest Heylo name
print("=== FUZZY MATCHES ===")
for eb_name in sorted(eb_names):
    match, score = process.extractOne(eb_name, heylo_names)
    status = "✓" if score >= 80 else "✗"
    print(f"{status} ({score}) EB: {eb_name}")
    print(f"          HY: {match}")
    print()

=== FUZZY MATCHES ===
✓ (86) EB: Canadá a través del arte: Tour guiado en español.
          HY: Inteligencia Artificial: Puerta al Futuro, Retos del Presente (2025-09-13)

✓ (86) EB: Cata de Cervezas Artesanales
          HY: Evento Deportivo: Club de Patinaje de La Red (2024-03-06)

✓ (86) EB: Conecta y Crece: Recomendaciones Inteligentes en La Red
          HY: ¡Los Lunes Toca Ser Red! (2023-12-04)

✓ (95) EB: Crea tu Negocio Navegando las Estructuras de Negocio en Canadá
          HY: Crea tu Negocio Navegando las Estructuras de Negocio en Canadá (2025-01-22)

✓ (86) EB: Cómo los Jóvenes pueden Prosperar en la Era de la IA
          HY: Tarde de Yoga! (2025-09-06)

✓ (86) EB: De Migrante a Líder: La Trayectoria de Miguel A.López
          HY: Tarde de Yoga! (2025-09-06)

✓ (86) EB: Domina el CELPIP: Claves para tu éxito en Canadá
          HY: Cómo Construir una Carrera Exitosa en la Industria del Fútbol (2025-03-12)

✓ (86) EB: Día Internacional de La Mujer: Latinas en Política Canadiense
          HY: Evento Social: Dia de Playa (2024-08-10)

✓ (95) EB: El Periodismo en Canadá: Desafíos y Oportunidades
          HY: El Periodismo en Canadá: Desafíos y Oportunidades (2024-10-22)

✓ (86) EB: El poder del español: How Spanish Got Me a Job
          HY: Inteligencia Artificial: Puerta al Futuro, Retos del Presente (2025-09-13)

✓ (86) EB: Evento Social Hispano en Calgary
          HY: Evento Deportivo: Club de Patinaje de La Red (2024-03-06)

✓ (86) EB: Evento Social Hispano en Montreal
          HY: Evento Deportivo: Club de Patinaje de La Red (2024-03-06)

✓ (86) EB: Evento Social Hispano en Ottawa
          HY: Evento Deportivo: Club de Patinaje de La Red (2024-03-06)

✓ (95) EB: Fortalece Tu Marca Profesional en Linkedin
          HY: Fortalece Tu Marca Profesional en LinkedIn (2025-09-10)

✓ (86) EB: Gala Hispana 2025
          HY: Inteligencia Artificial: Puerta al Futuro, Retos del Presente (2025-09-13)

✓ (86) EB: Guía para emprender sin miedo en Canada
          HY: Cómo Construir una Carrera Exitosa en la Industria del Fútbol (2025-03-12)

✓ (95) EB: Impulsa Tu Negocio TO - Tercera Edición 2025
          HY: Impulsa Tu Negocio TO - Tercera Edición 2025 (2025-09-27)

✓ (95) EB: Innovaciones en el futuro del Transporte Público en Canadá
          HY: Innovaciones en el futuro del Transporte Público en Canadá (2024-10-15)

✓ (95) EB: Mujeres Hispanas en el Sector de la Educación - Día de la Mujer
          HY: Mujeres Hispanas en el Sector de la Educación - Día de la Mujer (2025-03-08)

✓ (86) EB: Oportunidades Laborales en Canadá con Grupo Cartago
          HY: Inmigración: Express Entry – Bases con Nuevos Cambios y Programa (2023-11-01)

✓ (86) EB: Revoluciona tu Mundo: Chatbot & AI
          HY: Inmigración: Programa Caregiver para Conseguir tu Residencia (2023-11-16)

✓ (95) EB: SPEED NETWORKING DONDE LAS CONEXIONES CREAN OPORTUNIDADES REALES
          HY: SPEED NETWORKING DONDE LAS CONEXIONES CREAN OPORTUNIDADES REALES (2025-06-21)

✓ (95) EB: Segunda Feria Hispana con Organizaciones Sin Fines de Lucro
          HY: Segunda Feria Hispana con Organizaciones Sin Fines de Lucro (2025-05-03)

✗ (52) EB: Speak Dating
          HY: Diseña tu destino: Fotos Para Perfil de LinkedIn (2023-07-11)

✓ (86) EB: Speak Dating: Inglés y Francés
          HY: Cursos de francés con FutureOn Solutions (2025-03-06)

✓ (95) EB: Spring Party: Donde las Conexiones y el Buen Clima se Encuentran
          HY: Spring Party: Donde las Conexiones y el Buen Clima se Encuentran (2025-05-10)

✓ (95) EB: Sunset Social: ¡Conecta, comparte y ríe!
          HY: Sunset Social: ¡Conecta, comparte y ríe! (2025-08-23)

✓ (95) EB: Tarde de Conexiones en Niagara Falls
          HY: Tarde de Conexiones en Niagara Falls (2025-09-06)

✓ (95) EB: Tarde de Picnic: Cultura, Conexión y Comunidad!
          HY: Tarde de Picnic: Cultura, Conexión y Comunidad! (2025-07-12)

✓ (90) EB: Tarde de Yoga
          HY: Tarde de Yoga! (2025-09-06)

✓ (95) EB: Transforma tu Futuro: Optimiza tu Perfil de LinkedIn
          HY: Transforma tu Futuro: Optimiza tu Perfil de LinkedIn (2025-04-08)

✓ (95) EB: Tu Camino al Éxito en Canada con CIMT College
          HY: Tu Camino al Éxito en Canada con CIMT College (2025-03-28)

✓ (90) EB: Winter Party
          HY: Winter Party: Liberemos el Estrés (2025-02-22)

✓ (95) EB: Winter Party: Liberemos el Estrés
          HY: Winter Party: Liberemos el Estrés (2025-02-22)

✓ (95) EB: ¡La Red de Hispanos Llega a la Ciudad Vaquera de Canadá!
          HY: ¡La Red de Hispanos Llega a la Ciudad Vaquera de Canadá! (2025-08-09)